-- QUESTION ONE

SELECT * FROM forest_area
SELECT * FROM [land_area ]
SELECT * FROM REGIONS;

SELECT COUNT(DISTINCT COUNTRY_NAME) TOTAL_COUNTRIES FROM [land_area ];


-- QUESTION TWO

SELECT R.COUNTRY_NAME, INCOME_GROUP, TOTAL_AREA_SQ_MI FROM LAND_AREA L JOIN REGIONS R ON L.COUNTRY_CODE = R.COUNTRY_CODE 
WHERE TOTAL_AREA_SQ_MI BETWEEN 75000 AND 150000
--GROUP BY INCOME_GROUP;

SELECT * FROM (SELECT L.COUNTRY_NAME, INCOME_GROUP, COUNT(TOTAL_AREA_SQ_MI) OVER(PARTITION BY INCOME_GROUP) AS TOTAL_AREA
FROM LAND_AREA L JOIN REGIONS R ON L.COUNTRY_CODE = R.COUNTRY_CODE 
WHERE TOTAL_AREA_SQ_MI BETWEEN 75000 AND 150000) AS INCOME_TABLE;

-- QUESTION THREE
SELECT COUNT(COUNTRY_NAME) AS TOTAL_COUNTRIES FROM FOREST_AREA WHERE FOREST_AREA_SQKM >
(SELECT AVG(FOREST_AREA_SQKM) AS AVERAGE
                          FROM FOREST_AREA F JOIN REGIONS R ON F.country_code = R.COUNTRY_CODE WHERE INCOME_GROUP = 'HIGH INCOME')


SELECT COUNT(COUNTRY_NAME) FROM FOREST_AREA 

-- QUESTION FOUR

SELECT INCOME_GROUP, AVG(TOTAL_AREA_SQ_MI) AS AVERAGE FROM LAND_AREA L JOIN REGIONS R ON L.COUNTRY_CODE = R.COUNTRY_CODE GROUP BY INCOME_GROUP;

-- QUESTION FIVE 

SELECT INCOME_GROUP, AVG(FOREST_AREA_SQKM) AS AVERAGE FROM FOREST_AREA F JOIN REGIONS R ON F.COUNTRY_CODE = R.COUNTRY_CODE GROUP BY INCOME_GROUP;

-- QUESTION SIX 
SELECT DISTINCT REGION, COUNTRY_NAME,
FOREST_AREA_SQKM FROM (SELECT F.COUNTRY_NAME, REGION, FOREST_AREA_SQKM, 
                       DENSE_RANK() OVER(PARTITION BY REGION ORDER BY FOREST_AREA_SQKM DESC) POSITION
                       FROM FOREST_AREA F JOIN REGIONS R ON F.COUNTRY_CODE = R.COUNTRY_CODE) POSITION_TABLE
WHERE POSITION = 1



SELECT R.COUNTRY_NAME, REGION, SUM(FOREST_AREA_SQKM) FROM FOREST_AREA F JOIN REGIONS R ON F.COUNTRY_CODE = R.COUNTRY_CODE GROUP BY R.COUNTRY_NAME, REGION
ORDER BY SUM(FOREST_AREA_SQKM) DESC